messages:
  firstJoin:
    enabled: true
    message: '&b%player_display_name% &7 has joined for the first time!'
  join:
    enabled: true
    message: '&a--> &e%player_display_name%&a connected from &b%player_country% &r(&b%player_ip_masked%&r)&a.'
  quit:
    enabled: true
    message: '&c<-- &e%player_display_name%&c disconnected.'
  kick:
    enabled: true
    message: '&c<-- &e%player_display_name%&c was kicked (Reason: %reason%).'
GeoIP2:
  country:
    # enabled: true
    # databaseFilename: 'GeoLite2-Country.mmdb'
    url:
      download: 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key={LICENSE_KEY}&suffix=tar.gz'
      # sha256: 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key={LICENSE_KEY}&suffix=tar.gz.sha256'
  # city:
  #   enabled: false
  #   databaseFilename: 'GeoLite2-City.mmdb'
  #   url:
  #     download: 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key={LICENSE_KEY}&suffix=tar.gz'
  #     sha256: 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key={LICENSE_KEY}&suffix=tar.gz.sha256'
  # api:
  #   # countryやcityの設定より優先されます
  #   enabled: false
  #   # geolite.info or geoip.maxmind.com
  #   host: 'geolite.info'
  #   accountID: ~
  licenseKey: ''
