name: JoinPlus
main: com.github.hibi_10000.plugins.joinplus.JoinPlus
version: ${project.version}
api-version: 1.17
author: Hibi_10000
commands:
  joinplus:
    description: JoinPlus command.
    permission: joinplus.command
permissions:
  joinplus.command:
    description: Permission to use the /joinplus command.
    default: op
  joinplus.command.reload:
    description: Permission to use the /joinplus reload command.
    default: op
    children:
      joinplus.command: true
  joinplus.command.geoupdate:
    description: Permission to use the /joinplus geoupdate command.
    default: op
    children:
      joinplus.command: true
